package projectEuler;

import java.math.BigInteger;
import java.util.LinkedHashSet;

/*
 * Consider all integer combinations of aˆb for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
 * 
 * If they are then placed in numerical order, with any repeats removed, we get
 * the following sequence of 15 distinct terms:
 * 
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 * 
 * How many distinct terms are in the sequence generated by aˆb for 2 ≤ a ≤ 100
 * and 2 ≤ b ≤ 100?
 * 
 * COMPLETED ON 07/08/18
 */
public class Euler_29 {

	private static LinkedHashSet<BigInteger> terms = new LinkedHashSet<>();

	public static void main(String[] args) {
		for (int a = 2; a <= 100; a++) {
			pow(BigInteger.valueOf(a), 100);
		}

		System.out.println(terms.size());
	}

	private static BigInteger pow(BigInteger a, int b) {
		if (b == 1) {
			return a;
		} else {
			BigInteger result = a.multiply(pow(a, b - 1));
			terms.add(result);
			return result;
		}
	}
}
