package dev.bandeira.projecteulersolutions.problem12;

import java.util.HashMap;

/*
 * https://projecteuler.net/problem=12
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 * 
 * The first ten terms would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 * COMPLETED ON 19/02/18
 */
public class Problem12 {
	public static void main(String[] args) {
		Long curNumber = 2l;
		Integer divisors = 1;

		while (divisors < 500) {
			divisors = 1;
			curNumber++;
			Long triangularNmbr = getTriangularNmbr(curNumber);
			Long decoNmbr = triangularNmbr;
			HashMap<Integer, Integer> primeFactors = new HashMap<>();

			while (decoNmbr != 1) {
				for (int i = 2; i <= decoNmbr; i++) {
					if (decoNmbr % i == 0) {
						decoNmbr = decoNmbr / i;
						if (primeFactors.containsKey(i)) {
							primeFactors.put(i, primeFactors.get(i) + 1);
						} else {
							primeFactors.put(i, 1);
						}
						i--;
					}
				}
			}
			Object[] primeDivisors = primeFactors.keySet().toArray();
			for (int i = 0; i < primeDivisors.length; i++) {
				divisors = (primeFactors.get(primeDivisors[i]) + 1) * divisors;
			}

			System.out.println(curNumber + ", " + triangularNmbr + ", " + divisors);
		}

	}

	public static Long getTriangularNmbr(Long i) {
		return i * (i + 1) / 2;
	}
}
